### ISSUE TITLE
Not fully listing anymore

### ISSUE THREAD

**Issue by Slofe** [bewam/userscripts#4]
Hi there,

I used this script recently for the first time in a while and I've noticed that it lists up to 120 and then stops.  This happens regardless of what role I choose.  Any way of fixing this? Thanks.

**Comment by bewam** [comment]
As the script I wrote are in the same directory, I don't see which script you're talking about.
The fet' one ?  It doesn't work at all for me .

**Comment by Slofe** [comment]
Hi, yes the fet one. It just lists 20 profiles and the stops for me.  Is there any way of fixing it?

**Comment by Slofe** [comment]
So I just tried it with tampermonkey and violent monkey on firefox 59.02.04 and the it only goes up to 60 members then stops.  I get the exact same issue with tampermonkey on chrome as well. 

I am getting these errors in the code:

Uncaught TypeError: Cannot read property '1' of null
    at storeUser (userscript.html?id=e0f5e65e-0dbb-4e41-afed-7d80da31de2a:871)
    at HTMLDivElement.$.each (userscript.html?id=e0f5e65e-0dbb-4e41-afed-7d80da31de2a:793)
    at Function.each (userscript.html?id=e0f5e65e-0dbb-4e41-afed-7d80da31de2a:7)
    at Object.onMembersPage [as success] (userscript.html?id=e0f5e65e-0dbb-4e41-afed-7d80da31de2a:792)
    at j (userscript.html?id=e0f5e65e-0dbb-4e41-afed-7d80da31de2a:7)
    at Object.fireWith [as resolveWith] (userscript.html?id=e0f5e65e-0dbb-4e41-afed-7d80da31de2a:7)
    at x (userscript.html?id=e0f5e65e-0dbb-4e41-afed-7d80da31de2a:9)
    at XMLHttpRequest.eval (userscript.html?id=e0f5e65e-0dbb-4e41-afed-7d80da31de2a:9)

I removed the numbers in the brackets and now it filters all the pages again but returns no results.  As you can tell I'm pretty clueless when it comes to scripting! Hope the errors listed here can shed some light on the problem.

**Comment by bewam** [comment]
IMO, you'd better use the debugger to find where it fails rather than going blind and expecting. "the numbers in the bracket", if I'm right for the location, are matches from the string after the member's name. We don't have to modify anything there. The matches Array is like(example) ['27F sub','27','F','sub'], so [ 0:all the string, 1:age, 2:gender, 3:role ] in [an array](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array). "Cannot read property '1' of null" means that you're trying to get an indexed value of something that does'nt exists, so the Array is missing.
The best way is to place a breakpoint in the debugger at the said line and look for the local variables especially "user" one.

1) Can you tell me what's your operating system? [Android with Firefox Fennec ?](https://github.com/bewam/userscripts/issues/1#issuecomment-217441515)
2) Do you have profiles **shown**?
I use FF59+ Linux but with greasemonkey, just need a little tweak, with either a polyfill or the replacement of GM_addStyle, removed in GM4.
I have tried  tampermonkey and chromium(chrome), I load 10 pages and obtain 150+ results on both.

**Comment by Slofe** [comment]
I'm not sure why the array would be missing.  It actually shows profiles up to a certain point and then stops.  Strangely it will list, say, 45 profiles in one location then stop and in another one only 3 and then stop.  I've tried this in small towns and large cities and the results are the same, more in some and less in others.   

Sorry I thought the errors I listed would give you the location of the error in the script.  The location is line 921:

C[1] = matches[1]; (X)

My operating system is Windows 7 with Firefox version 59.02.04

The same happens on Chrome too.  

I updated to your new version but still getting the same results.

**Comment by bewam** [comment]
I was pretty sure the line you talked about was this one. The console can give the wrong line because it cross through other scripts (GM, tamper...).
The major problem is the page got doesn't show profiles or page not exists. For the second postulate, it's simple, network console would show a 404 error. A bit strange, but ... have you tried to go manually where the pages are ? Or go to the pages just before the one not fetched and run for a few pages or the rest of the location results.
The weight of the pages can be a clue.

I can test on Win7 today.

The new version just allow to run in greasemonkey 4+.

**Comment by bewam** [comment]
I'm sorry. I can't reproduce this issue. I tested under win7 with FF and GreaseMonkey, no profile is missing.
I suspect fetlife server to limit your traffic. Maybe do less filtering or increase  "const FETCH_LATENCY = 1500;" to 2000 or 3000 @line 22, they are milliseconds, take care of what you do. it will be slower, but will reduce traffic.
If you find any suspect behavior, tell it.

**Comment by bewam** [comment]
If you really want to spend some time to help.
you could add a "`console.log(users)`" [line 824](https://github.com/bewam/userscripts/blob/d487580109b411821b813050cd3ceb402fbe9f04/fetlife_filter_members/fetlife_filter_members_ASL-name-role-status-avatar_.user.js#L824). The script log is enabled actually -my bad- you should see a JQuery Object in the console(_ctrl+alt+k_) like `{length :..., ... }`. If the page is loaded correctly, the **length should not be equal 0**, so the problem should come from the server.
Or learn a bit of debugger, set a breakpoint @[line 824](https://github.com/bewam/userscripts/blob/d487580109b411821b813050cd3ceb402fbe9f04/fetlife_filter_members/fetlife_filter_members_ASL-name-role-status-avatar_.user.js#L824). and watch variables for users and/or data.
At that moment, in the script the argument `data` is the content of a page loaded in background.

**Comment by Slofe** [comment]
Hey, sorry for late reply I've been away. I think the problem is the server end because sometimes it lists fully, sometimes a little bit and sometimes not at all. This is different every time, for different parameters search and for different locations. I will try your suggestions when I get time, thanks.

**Comment by bewam** [comment]
mh, ok, I may say what's wrong and gonna try something.

**Comment by Slofe** [comment]
Great, it lists group members fully only locations it's doesn't. Also, please tell me where to make a donation to you.

**Comment by bewam** [comment]
I didn't test it. "only locations it's doesn't." means? When you're in places pages, like "administrative_areas/" in url?
With this version, the "only with avatar" must stay unchecked. The problem come effectively from their server. They block traffic if you do too much error, here is "http 304 forbidden", because you're "not logged" when fetching other pages than the one you're on, something called http referrer is not sent correctly, XHR can't send the good one (page where images are). Tried, but it's a browser security issue.
I don't have a donation system. I may. I'm pleased, that's enough for now.

**Comment by Slofe** [comment]
I just updated and it doesn't load at all now, this is on violent monkey for Firefox. What I meant by locations was when I search the list of people in my city it only searches 60 people before stopping but when I searched a group membership it searched the whole list.

**Comment by bewam** [comment]
It was missing a colon, my bad.
It seems to work fine for me now, even administrative_area page... Just made a 2909 members search.
Maybe I can make a difference between profile which has an avatar and other.

**Comment by Slofe** [comment]
Great, so it's listing all members again but there is one problem. It doesn't show any of the avatars like it used to. It just shows a red box where the avatar should be with the member's name inside. This happens whether I check or uncheck the 'only with avatar' box.

**Comment by bewam** [comment]
Read 4 posts above... "They block traffic", you cannot have both anymore, it's #4 issue OR avatars. So I placed a redbox to say "that member has an avatar" Or We must reforge the whole script which may take... forget about it.
I'm sorry about it. It's actually the only way without spending too much time for a so few use.

**Comment by Slofe** [comment]
Oh OK, that's a bit of a drag but at least it lists again I guess. Thanks again for your work 🙂

**Comment by Slofe** [comment]
Hey how's it going? Just wanted to draw attention to the fact there's another script from way back, the meitar asl one, that still works and lists people with photos.  It's very clunky but gets the job done, is there a way to incorporate some of that into your script? 

I also used the old script for group searches and it lists everyone in the group with their pictures.  I wonder why they blocked location search and not group search? Using the script as it is now for location search is as time consuming as just looking through like normal.  I hope you come up with a way of fixing it.  If not nevermind, I've had a pretty good run :)

**Comment by bewam** [comment]
I know the script you're talking about. We don't aim the same goal. My script doesn't share any data with any other site. My script is only between you and fetlife. It's interesting to know that getting the images is possible. I really wonder how it manages to do so.
The guy you talk about is engineer and surely knows better the way to deal with ajax and webpages. I'm not.
I don't really have much time to spend on it for now, sorry.

**Comment by Slofe** [comment]
Thanks for the reply.  Yeah the guy who wrote that script has really poor communication skills so it's impossible to talk to him, I think he's lost interest in maintaining that script.  No problem about lack of time, like I said I had a good run with your script.  Hope you come back to it in future.  Have a good Christmas!
